language: java
script:
- ant -f ./client-libraries/java/rest-client/build.xml -lib ./client-libraries/java/rest-client/lib
  deploy
before_install:
- cp settings.xml ${HOME}/.m2/settings.xml
after_success:
- echo "deploy completed."
branches:
  only:
  - master
env:
  global:
  - secure: JLi7Nhp/kr5Nv8e3Ldg0jEyitvjSljZwNLlR5SHphvUlV7POvVNqXJ994358wySD9sDEFCupHdO5sCmIkw4f9rQfEOB7uCWVr3qBR7qalQAeSCSjxkPAZMB7oZZrlgBR+aviwiUHlElVB+Qn6QtUWZfwT5qmCzKDTFTPiDaby2s=
  - secure: MN7EKwGBOUQ9FDA4TXnq4lDprIBXmkXHMsp6jSBhdyXaZt0ix/FcmCqCYNumxrAVxquHRmcgb6hI5EuqZNHfI0hTvhbPGG9MIKweMNzWC3O9Lw44ufvog2wa2Xa/+hJDHNSLsL5HiF4sWy//V7/GcfYnIpdl/GN43dKBsd8FooQ=
